# Site
title:              Ben Montgomery
bio:                'Some guy who really likes optimizing code performance.'
description:        "Developer with a focus on back-end development, code optimization, and parallelization."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/markus-spiske-code-bg.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://nyctanthous.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Social
github-url:         nyctanthous
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           ben-montgomery-245245b4

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
